PROGRAM=hello_telehash
CFLAGS += -I./telehash/include \
          -I/Users/rodrigopex/Tools/esp-open-sdk/esp-open-rtos/lwip/lwip/src/include \
          -ffunction-sections \
          -fdata-sections \
          -std=gnu99 -D_ESP8266EX_
include ../../common.mk
